### ISSUE TITLE
Team Editor ?

### ISSUE THREAD

**Issue by alsciende** [gabriel-hook/contest-of-champions#2]
I would like to be able to select some champions and see the activated synergies between them. 

This could be done in the Synergy Network: you would only need to let us select more than one champion.

Then the synergy between 2 selected champions need to be differentiated from the synergy between a selected champion and an unselected champion:
- make the arrow bigger when the synergy is activated
- or make the arrow colorless when the synergy is not activated
- or display a count of the activated synergies

**Comment by gabriel-hook** [comment]
Added Multi-select. If you Shift-click or Ctrl-click you can select multiple champions.

The legend will show only the active synergies with amount %s when selected are > 1

**Comment by alsciende** [comment]
Awesome, thanks!

How can I unselect a champion once I've selected two or more champions?

**Comment by gabriel-hook** [comment]
Shift-click will only add a selection.

Ctrl-click will toggle a selection (use this to deselect while keeping the current team).
