### ISSUE TITLE
Duplicate Class Weights behaving strangely

### ISSUE THREAD

**Issue by alsciende** [gabriel-hook/contest-of-champions#3]
I'm trying to understand the behavior of the Duplicate Class Weights. I have a roster of 22 champions. When I ask the tool to build teams of 3 champions in the "Balanced" DCW setting, I have 3 teams with a duplicate class. Now, I'd like to tell the tool to increase the penalty on duplicate classes, so that it will try to find good teams without any duplicate class. So I go to the Advanced Settings, but my first problem is that I don't understand the settings. The scales go from 0 to 100 for 4 different variables: Double, Triple, Quadruple, Quintuple. I don't understand what the variables mean, and I don't understand what their values mean. I'm expecting a single variable "Penalty for duplicate class", with a value from "Low" to "High", or something like that.

Then, I take a leap of faith and choose a different preset. "All", for example. All the variables are set to 100. But when I re-build, I now have a team with 3 Tech champions in addition to my previous 3 teams with a duplicate class. So that's worse for my use case.

I go back to the Advanced Settings and now choose "None", although it doesn't sound like what I need. And surprise, when I re-build the teams, I have the exact same teams with 3 teams with a duplicate class and 1 team with 3 Tech champions. So "All" === "None".

I really love your tool, as do most CoC players. Could you please make the settings more user-friendly, and let us know how to increase the penalty on Duplicate Class to get teams without duplicates? 

For reference, my roster is:
- Cap. Marvel 3¤
- Cap. Marvel 4¤
- Gamora 3¤
- Thor 3¤
- Iron Man 4¤
- Ultron 4¤
- Iron Man 3¤
- Star-Lord 3¤
- The Vision 3¤
- Storm 4¤
- Wolverine 4¤
- Storm 3¤
- Daredevil 4¤
- Black Panther 3¤
- Black Widow 3¤
- Cap America 4¤
- Spider-Man 4¤
- Cap America 3¤
- Dr Strange 4¤
- Iron Fist 4¤
- Juggernaut 4¤
- Iron Fist 3¤

**Comment by alsciende** [comment]
I am on the algorithm "Shuffle". And the best settings I could find was to put all scales on "1". With that DCW settings, I was able to get 6 teams with no duplicate and 1 team with 1 duplicate class.

**Comment by gabriel-hook** [comment]
It's actually working as intended,  but I agree that you can set it up to behave strangely.  The default settings give the best behavior.

**Comment by Alsciende** [comment]
> The default settings give the best behavior.

The test case I provided actually proves the contrary. The default settings give quite a bad result. It's possible to do better by setting everything to 1.
