### ISSUE TITLE
Synergy with a champion is counted twice if that champion is present twice in the team

### ISSUE THREAD

**Issue by alsciende** [gabriel-hook/contest-of-champions#4]
Say the team is Drax 2*, Gamora 2*, Gamora 1*. The synergy from Drax to Gamora is counted twice. That's not what happens in-game.

![greenshot_2015-10-22_10-05-37](https://cloud.githubusercontent.com/assets/391974/10660051/7de2b02c-78a4-11e5-8ecc-1907546b2b51.png)

**Comment by gabriel-hook** [comment]
I had some pretty bad logic handling that! It should be fixed now!
