### ISSUE TITLE
Team building not loading

### ISSUE THREAD

**Issue by Gekkoyolo** [gabriel-hook/contest-of-champions#5]
Hi, 

I have been trying to access the team building option, but i have a loading error. The kog turns as if it was loading, but the loading bar stays blank. I have tried through three different navigators. 
It has worked before. A few of my friends have also had this issue.

Thanks, and great website!

**Comment by gabriel-hook** [comment]
I've been working on a rewrite that will be better,  but I'll fix that tonight ,  I must have messed up a build path.

**Comment by gabriel-hook** [comment]
As a side note, the rewrite can be reached at http://gabriel-hook.github.io/contest-of-champions/es6 for right now, and it will end up being a combination of synergy/roster/teams/guides rebuilt from the ground up.

**Comment by gabriel-hook** [comment]
# Fixed!
